services:
  - type: web
    name: laravel-api
    env: php
    plan: free
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=127.0.0.1 --port=8000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
